name: Lint and Format Code Base

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Lint Code Base
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: 'master'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn install
          yarn format
          yarn lint
